defmodule Weakty.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  # subtype already added by 20260228000000_add_subtype_to_entities.exs
  def up do
  end

  def down do
  end
end
