defmodule Weakty.Repo.Migrations.UniqueSlugs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:posts, [:slug], name: "posts_unique_slug_index")

    create unique_index(:links, [:slug], name: "links_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:links, [:slug], name: "links_unique_slug_index")

    drop_if_exists unique_index(:posts, [:slug], name: "posts_unique_slug_index")
  end
end
