defmodule Weakty.Repo.Migrations.AddEntityTags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:entity_tags, primary_key: false) do
      add :tag_id, references(:tags, column: :id, name: "entity_tags_tag_id_fkey", type: :uuid),
        null: false

      add :entity_id,
          references(:entities, column: :id, name: "entity_tags_entity_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:entity_tags, [:entity_id, :tag_id],
             name: "entity_tags_unique_entity_tag_index"
           )

    alter table(:entities) do
      remove :tags
    end
  end

  def down do
    # alter table(:entities) do
    # This is the `down` migration of the statement:
    #
    #     remove :tags
    #
    # 
    # add :tags, {:array, :text}, default: []
    # end
    # 
    drop_if_exists unique_index(:entity_tags, [:entity_id, :tag_id],
                     name: "entity_tags_unique_entity_tag_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `entity_tags` table without the `entity_tags_entity_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `entity_tags` table without the `entity_tags_tag_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:entity_tags)
  end
end
