defmodule Weakty.Repo.Migrations.AddEntityFieldsAndLinkSlug do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:links) do
      add :slug, :text, null: false
    end

    rename table(:entities), :description, to: :content

    alter table(:entities) do
      add :slug, :text, null: false
      add :source_path, :text, null: false
      add :hero_url, :text
      add :thumbnail_url, :text
      add :rating, :bigint
      add :status, :text
      add :favourite, :boolean
    end
  end

  def down do
    alter table(:entities) do
      remove :favourite
      remove :status
      remove :rating
      remove :thumbnail_url
      remove :hero_url
      remove :source_path
      remove :slug
    end

    rename table(:entities), :content, to: :description

    alter table(:links) do
      remove :slug
    end
  end
end
