defmodule Weakty.Repo.Migrations.AddLinkOgFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # attribution/attribution_url already added by 20260227100000_consolidate_tils_and_quotes_into_posts.exs
    # subtype already added by 20260228000000_add_subtype_to_entities.exs

    alter table(:links) do
      add :og_title, :text
      add :og_description, :text
      add :og_image, :text
    end
  end

  def down do
    alter table(:links) do
      remove :og_image
      remove :og_description
      remove :og_title
    end
  end
end