defmodule Weakty.Repo.Migrations.CreatePostTagsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:post_tags, primary_key: false) do
      add :tag_id, references(:tags, column: :id, name: "post_tags_tag_id_fkey", type: :uuid),
        null: false

      add :post_id, references(:posts, column: :id, name: "post_tags_post_id_fkey", type: :uuid),
        null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:post_tags, [:post_id, :tag_id], name: "post_tags_unique_post_tag_index")
  end

  def down do
    drop_if_exists unique_index(:post_tags, [:post_id, :tag_id],
                     name: "post_tags_unique_post_tag_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `post_tags` table without the `post_tags_post_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `post_tags` table without the `post_tags_tag_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:post_tags)
  end
end