defmodule Weakty.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tils, primary_key: false) do
      add :user_id, references(:users, column: :id, name: "tils_user_id_fkey", type: :uuid),
        null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :published_at, :utc_datetime_usec
      add :public, :boolean, null: false
      add :slug, :text, null: false
      add :html, :text
      add :body, :text, null: false
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:tils, [:slug], name: "tils_unique_slug_index")

    create table(:til_tags, primary_key: false) do
      add :tag_id, references(:tags, column: :id, name: "til_tags_tag_id_fkey", type: :uuid),
        null: false

      add :til_id, references(:tils, column: :id, name: "til_tags_til_id_fkey", type: :uuid),
        null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:til_tags, [:til_id, :tag_id], name: "til_tags_unique_til_tag_index")

    create table(:quotes, primary_key: false) do
      add :user_id, references(:users, column: :id, name: "quotes_user_id_fkey", type: :uuid),
        null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :public, :boolean, null: false
      add :slug, :text, null: false
      add :attribution_url, :text
      add :attribution, :text
      add :body, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:quotes, [:slug], name: "quotes_unique_slug_index")

    create table(:quote_tags, primary_key: false) do
      add :tag_id, references(:tags, column: :id, name: "quote_tags_tag_id_fkey", type: :uuid),
        null: false

      add :quote_id,
          references(:quotes, column: :id, name: "quote_tags_quote_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:quote_tags, [:quote_id, :tag_id],
             name: "quote_tags_unique_quote_tag_index"
           )
  end

  def down do
    drop_if_exists unique_index(:quote_tags, [:quote_id, :tag_id],
                     name: "quote_tags_unique_quote_tag_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `quote_tags` table without the `quote_tags_quote_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `quote_tags` table without the `quote_tags_tag_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:quote_tags)

    drop_if_exists unique_index(:quotes, [:slug], name: "quotes_unique_slug_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `quotes` table without the `quotes_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:quotes)

    drop_if_exists unique_index(:til_tags, [:til_id, :tag_id],
                     name: "til_tags_unique_til_tag_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `til_tags` table without the `til_tags_til_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `til_tags` table without the `til_tags_tag_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:til_tags)

    drop_if_exists unique_index(:tils, [:slug], name: "tils_unique_slug_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `tils` table without the `tils_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:tils)
  end
end