defmodule Weakty.Repo.Migrations.AddProjects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:projects, primary_key: false) do
      add :user_id, references(:users, column: :id, name: "projects_user_id_fkey", type: :uuid),
        null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :images, {:array, :text}, default: []
      add :end_date, :date
      add :start_date, :date
      add :links, {:array, :map}, default: []
      add :published_at, :utc_datetime_usec
      add :public, :boolean, null: false
      add :featured, :boolean, null: false
      add :project_status, :text, null: false
      add :status, :text, null: false
      add :excerpt, :text
      add :featured_image, :text
      add :html, :text
      add :markdown, :text, null: false
      add :slug, :text, null: false
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:projects, [:slug], name: "projects_unique_slug_index")

    create table(:project_tags, primary_key: false) do
      add :tag_id, references(:tags, column: :id, name: "project_tags_tag_id_fkey", type: :uuid),
        null: false

      add :project_id,
          references(:projects, column: :id, name: "project_tags_project_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:project_tags, [:project_id, :tag_id],
             name: "project_tags_unique_project_tag_index"
           )
  end

  def down do
    drop_if_exists unique_index(:project_tags, [:project_id, :tag_id],
                     name: "project_tags_unique_project_tag_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `project_tags` table without the `project_tags_project_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `project_tags` table without the `project_tags_tag_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:project_tags)

    drop_if_exists unique_index(:projects, [:slug], name: "projects_unique_slug_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `projects` table without the `projects_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:projects)
  end
end