defmodule Weakty.Repo.Migrations.AddMediaLogs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:media_logs, primary_key: false) do
      add :user_id, references(:users, column: :id, name: "media_logs_user_id_fkey", type: :uuid),
        null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :published_at, :utc_datetime_usec
      add :favourite, :boolean, null: false
      add :public, :boolean, null: false
      add :external_url, :text
      add :notes, :text
      add :rating, :bigint
      add :date_finished, :date
      add :date_started, :date
      add :date_consumed, :date
      add :status, :text, null: false
      add :thumbnail_url, :text
      add :date_published, :date
      add :creator, :text
      add :media_type, :text, null: false
      add :slug, :text, null: false
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:media_logs, [:slug], name: "media_logs_unique_slug_index")

    create table(:media_log_tags, primary_key: false) do
      add :tag_id,
          references(:tags, column: :id, name: "media_log_tags_tag_id_fkey", type: :uuid),
          null: false

      add :media_log_id,
          references(:media_logs,
            column: :id,
            name: "media_log_tags_media_log_id_fkey",
            type: :uuid
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:media_log_tags, [:media_log_id, :tag_id],
             name: "media_log_tags_unique_media_log_tag_index"
           )
  end

  def down do
    drop_if_exists unique_index(:media_log_tags, [:media_log_id, :tag_id],
                     name: "media_log_tags_unique_media_log_tag_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `media_log_tags` table without the `media_log_tags_media_log_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `media_log_tags` table without the `media_log_tags_tag_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:media_log_tags)

    drop_if_exists unique_index(:media_logs, [:slug], name: "media_logs_unique_slug_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `media_logs` table without the `media_logs_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:media_logs)
  end
end
