defmodule Weakty.Repo.Migrations.AddPublicToLinks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:links) do
      add :public, :boolean, null: false
    end
  end

  def down do
    alter table(:links) do
      remove :public
    end
  end
end
