defmodule Weakty.Repo.Migrations.AddElapsedMinutesToFocusSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:focus_sessions) do
      add :elapsed_minutes, :bigint
    end
  end

  def down do
    alter table(:focus_sessions) do
      remove :elapsed_minutes
    end
  end
end