defmodule Weakty.Repo.Migrations.AddEntities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:entities, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :public, :boolean, null: false
      add :published_at, :utc_datetime_usec, null: false
      add :url, :text
      add :description, :text
      add :title, :text
      add :source_id, :uuid, null: false
      add :entity_type, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:entities, [:entity_type, :source_id],
             name: "entities_unique_source_index"
           )
  end

  def down do
    drop_if_exists unique_index(:entities, [:entity_type, :source_id],
                     name: "entities_unique_source_index"
                   )

    drop table(:entities)
  end
end
