defmodule Weakty.Repo.Migrations.AddTags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tags, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :slug, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:tags, [:name], name: "tags_unique_name_index")

    create unique_index(:tags, [:slug], name: "tags_unique_slug_index")

    create table(:link_tags, primary_key: false) do
      add :tag_id, references(:tags, column: :id, name: "link_tags_tag_id_fkey", type: :uuid),
        null: false

      add :link_id, references(:links, column: :id, name: "link_tags_link_id_fkey", type: :uuid),
        null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:link_tags, [:link_id, :tag_id], name: "link_tags_unique_link_tag_index")

    alter table(:entities) do
      add :tags, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:entities) do
      remove :tags
    end

    drop_if_exists unique_index(:link_tags, [:link_id, :tag_id],
                     name: "link_tags_unique_link_tag_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `link_tags` table without the `link_tags_link_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `link_tags` table without the `link_tags_tag_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:link_tags)

    drop_if_exists unique_index(:tags, [:slug], name: "tags_unique_slug_index")

    drop_if_exists unique_index(:tags, [:name], name: "tags_unique_name_index")

    drop table(:tags)
  end
end
