defmodule Weakty.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`

  NOTE: attribution and attribution_url were already added to posts by
  20260227100000_consolidate_tils_and_quotes_into_posts.exs — no-op here.
  """

  use Ecto.Migration

  def up do
  end

  def down do
  end
end
