defmodule Weakty.Repo.Migrations.ExtendTags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tags) do
      add :public, :boolean
      add :featured_image, :text
      add :description, :text
      add :description_html, :text
    end
  end

  def down do
    alter table(:tags) do
      remove :description_html
      remove :description
      remove :featured_image
      remove :public
    end
  end
end