defmodule Weakty.Repo.Migrations.AddPosts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:posts, primary_key: false) do
      add :user_id, references(:users, column: :id, name: "posts_user_id_fkey", type: :uuid),
        null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :published_at, :utc_datetime_usec
      add :public, :boolean, null: false
      add :featured, :boolean, null: false
      add :status, :text, null: false
      add :excerpt, :text
      add :featured_image, :text
      add :html, :text
      add :markdown, :text, null: false
      add :slug, :text, null: false
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `posts` table without the `posts_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:posts)
  end
end
