defmodule Weakty.Repo.Migrations.AddFocusSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:focus_sessions, primary_key: false) do
      add :project_id,
          references(:projects, column: :id, name: "focus_sessions_project_id_fkey", type: :uuid)

      add :user_id,
          references(:users, column: :id, name: "focus_sessions_user_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :completed_at, :utc_datetime_usec
      add :break_started_at, :utc_datetime_usec
      add :started_at, :utc_datetime_usec
      add :status, :text, null: false
      add :break_duration_minutes, :bigint, null: false
      add :duration_minutes, :bigint, null: false
      add :notes, :text
      add :category, :text
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `focus_sessions` table without the `focus_sessions_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `focus_sessions` table without the `focus_sessions_project_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:focus_sessions)
  end
end