defmodule Weakty.Repo.Migrations.AddPostType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add :post_type, :text, null: false, default: "post"
    end
  end

  def down do
    alter table(:posts) do
      remove :post_type
    end
  end
end
