defmodule Weakty.Repo.Migrations.AddOgImagePinnedToLinks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:links) do
      add :og_image_pinned, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:links) do
      remove :og_image_pinned
    end
  end
end